name: Get Proxies

# 触发条件
on:
  workflow_dispatch:

  schedule:
    # - cron: '*/5 * * * *'
    # 表达式生成  https://crontab.guru/
    - cron: '0 0-23/3 * * *'

jobs:
  main:
    name: Merge & speedtest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: Install dependencies
      run: pip install -r ./utils/requirements.txt
    - name: Start Clash proxy environment
      run: |
        sudo sh ./utils/scripts/set_proxy.sh
    - name: Merge & speedtest
      run: |
        chmod +x ./utils/subconverter/subconverter-linux-amd64 && chmod +x ./utils/litespeedtest/lite-linux-amd64
        python ./utils/main.py
    - name: Commit change
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin master
        git add ./sub
        git add ./update
        git add ./Eternity
        git add ./Eternity.yaml
        git add README.md
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S')合并节点"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PUSH_TOKEN }}
        branch: master
